src/renderer/app/router.tsx
- 관련 링크: https://stackoverflow.com/questions/36505404/how-to-use-react-router-with-electron
=> fix: electron 는 파일기반이라 hash router 변경

src/renderer/app/router.tsx, src/renderer/features/update-pomodoro/index.ts, src/renderer/pages/home.tsx, src/renderer/pages/pomodoro.tsx, src/renderer/pages/second.tsx, src/renderer/shared/constants/path.ts, src/renderer/shared/hooks/index.ts, src/renderer/shared/hooks/use-stopwatch.ts, src/renderer/shared/hooks/use-timer.ts
- 타이머 훅 구현
문제 없어보여서 일단 렌더러에 둠!
=> feat: 타이머 훅 구현

src/renderer/app/provider.tsx, src/renderer/features/update-pomodoro/hooks/usePomodoroMutation.ts
- 모든 mutation 요청에 대해서 마지막 요청 한번만 보내도록 설정
- (테스트용) 마지막 요청의 요청값을 아예 변경해서 보내도록 설정
- 나중에 서버 연결할 때 설정해놓은 부분은 비활성화 or 개정해둬야할 듯 ㅋㄷㅋㄷ
=> feat: 오프라인 -> 온라인일때 쌓인 요청 한번에 보내는것 확인

package.json, src/renderer/app/provider.tsx, src/renderer/pages/pomodoro.tsx, src/renderer/shared/ui/carousel.tsx, src/renderer/shared/ui/drawer.tsx, src/renderer/shared/ui/index.ts, src/renderer/shared/ui/toast.tsx, src/renderer/shared/ui/toaster.tsx, src/renderer/shared/ui/use-toast.ts, yarn.lock
- shadcn/ui 의 drawer & toast 추가 및 적용해봄
=> feat: drawer (+ toast) 컴포넌트 추가

package.json, src/renderer/app/index.css, src/renderer/pages/home.tsx, src/renderer/shared/ui/button.tsx, src/renderer/shared/ui/drawer.tsx, src/renderer/shared/ui/index.ts, src/renderer/shared/ui/select.tsx, src/renderer/shared/ui/toast.tsx, src/renderer/shared/ui/toggle-group.tsx, src/renderer/shared/ui/toggle.tsx, tailwind.config.js, yarn.lock
- Typo 를 추가하였습니다. `className`에 바로 작성해주기 위해 (ex. `className="header-1"`) [@layer](https://tailwindcss.com/docs/adding-custom-styles#using-css-and-layer)를 이용하였습니다. Text 커스텀 컴포넌트를 따로 만들까도 생각해보았지만 텍스트가 있는 곳에 항상 `<Text></Text>` 를 작성해주어야 된다는 불편함이 있다고 생각하여 별도의 유틸리티 타입으로 정의해주었습니다.
- 시멘틱한 색상 토큰들을 `tailwind.config.js` >  colors의 extend로 추가하였습니다.
- 버튼 컴포넌트 (Box, Text, Round) 를 추가하였습니다.
- Select 컴포넌트를 추가하였습니다. shadcn/ui 의 Toggle Group / Toggle 컴포넌트를 이용하였습니다.
- home.tsx 에 예시 컴포넌트들을 추가하였습니다.
- 토글 컴포넌트를 추가하였습니다.
=> feat: 디자인 시스템 추가 (버튼, select, 타이포, 토글)

package.json, src/renderer/pages/home.tsx, src/renderer/pages/pomodoro.tsx, src/renderer/shared/assets/svgs/placeholder.svg, src/renderer/shared/ui/icon.tsx, src/renderer/shared/ui/index.ts, src/renderer/shared/ui/toast.tsx, src/renderer/shared/ui/toaster.tsx, src/renderer/shared/ui/tooltip.tsx, src/renderer/shared/ui/use-toast.ts, yarn.lock
- 작업 나누기로 했던 컴포넌트들 추가함
- typography는 아직 없어서 수동으로 추가해둠. 나중에 바꿀 예정~~
=> feat: 아이콘, 토스트, 툴팁 컴포넌트 추가

src/renderer/pages/onboarding.tsx, src/renderer/shared/ui/carousel.tsx
- 하면서 캐로셀 쪽 일부 기능추가함~
- 대충 요런 느낌임
=> feat: 온보딩 페이지 ui 구현

src/renderer/pages/selection.tsx, src/renderer/shared/ui/icon.tsx, src/renderer/shared/ui/toaster.tsx
- api 연동은 아직 못하고 현재 디자인 가이드 나온 정도만 붙임
https://github.com/user-attachments/assets/acbb6f7b-2194-4382-be6b-dbae2b56a96d
=> feat: 고양이 선택 페이지 ui 구현

src/renderer/pages/onboarding.tsx, tailwind.config.js
- 화면설계서 맞춰서 일부 수정함
- 화면 높이에 맞춰 상단 간격 주는거 생각보다 안이뻐서 일단 중앙정렬로 처리함..!
=> feat: 온보딩 페이지 일부 스타일 수정

src/renderer/app/router.tsx, src/renderer/pages/home.tsx, src/renderer/pages/naming.tsx, src/renderer/pages/selection.tsx, src/renderer/shared/assets/svgs/back.svg, src/renderer/shared/constants/path.ts, src/renderer/shared/ui/frame.tsx, src/renderer/shared/ui/icon.tsx, src/renderer/shared/ui/index.ts, src/renderer/shared/ui/tooltip.tsx
- 고양이 이름짓기 페이지 ui 추가함
- nav bar, bottom bar를 사용하기 위한 frame이라는 컴포넌트 추가함
- frame 컴포넌트 고양이 선택 페이지에도 적용함
https://github.com/user-attachments/assets/ecff2426-3a8a-46b9-9eda-5449f060988e
- ui 만들고 디테일함은 api 연동하면서 좀 더 잡을 예정!
=> feat: 고양이 이름짓기 페이지 ui 구현

src/renderer/pages/pomodoro.tsx, src/renderer/shared/utils/time.ts, src/renderer/widgets/pomodoro/ui/focus-screen.tsx
- handleReset, handleEnd시 타이머가 stop 하도록 수정하였습니다.
- handleEnd 시에는 지금까지 진행한 뽀모도로를 저장하도록 하였습니다.
- 툴팁 메세지를 수정하였습니다. (집중모드 / 집중시간 초과 모드)
=> feat: 집중 페이지 수정 (handleReset, handleEnd, 툴팁메세지)

package.json, src/renderer/entities/pomodoro/types.ts, src/renderer/pages/pomodoro.tsx, src/renderer/shared/ui/icon.tsx, src/renderer/vite-env.d.ts, src/renderer/widgets/pomodoro/ui/rest-screen.tsx, vite.renderer.config.ts, yarn.lock
- 휴식 페이지 ui 구현함
- 휴식 페이지 내 아이콘 색상 변경을 위해 svgr 도입
- 휴식 페이지에서 집중 시간 조정하는거 추가함. TODO 주석도 남김
=> feat: 휴식 페이지 ui 및 로직 일부 구현

src/renderer/features/category/index.ts, src/renderer/features/category/ui/category-chip.tsx, src/renderer/pages/pomodoro.tsx, src/renderer/shared/hooks/use-timer.ts, src/renderer/widgets/pomodoro/ui/rest-screen.tsx, src/renderer/widgets/pomodoro/ui/rest-wait-screen.tsx
- 뇌 정지 이슈로 주석을 좀 달아놨습니다,,,
- 우선 임시로 테스트하기 위해 시간을 짧게 설정해두었습니다.
=> feat: 휴식 대기 페이지 추가

src/renderer/app/router.tsx, src/renderer/features/time/hooks/use-focus-notification.ts, src/renderer/pages/home.tsx, src/renderer/pages/mypage.tsx, src/renderer/pages/onboarding.tsx, src/renderer/shared/constants/keys.ts, src/renderer/widgets/pomodoro/ui/home-screen.tsx
- 유저 flow에 맞춰 기능 추가함
- 새로고침 대응 안할려고 memory router로 변경
- 추가로 localstorage key 하나에 모음
- 마이페이지 고양이 이름 내 고양이 이름으로 변경
=> feat: 유저 flow 적용 및 기타

.github/workflows/bump-up.yml, .github/workflows/release.yml, src/renderer/pages/onboarding.tsx
- 지금 배포가 tag가 생길때마다 action이 돌고 그런데
- 이럴바에 main 브랜치에 머지될 때 마다 tagging 하게 하는게 좋을 것 같아서 적용함
- main에 머지할때 `#major`  or `#minor` or `#patch` 3개 중 하나 커밋메시지에 포함시키면 
- 자동으로 버전업 됩니다유 
- 추가로 온보딩 문구 내맘대로 바꿨습니다~~
=> feat: main 브랜치 머지할때 자동 tagging

src/renderer/shared/hooks/use-timer.ts
=> fix: 타이머 정상적으로 돌아가도록 수정

.github/workflows/release.yml, package.json, src/renderer/app/index.tsx, src/renderer/shared/utils/datadog.ts, src/renderer/shared/utils/index.ts, src/renderer/vite-env.d.ts, vite.renderer.config.ts, yarn.lock
- Real User Monitoring 기능을 사용하기 위한 셋팅
- 관련 환경변수 시크릿값은 datadog 들어가면 볼 수 있음
- 일단 로컬에서 적용했을땐 잘되는듯!
=> feat: datadog rum 적용

.github/workflows/bump-up.yml
- main 머지될 때마다 버전업 되는게 거슬리기도 하고 
- skip 하고 싶을 때도 있어서 추가함!
=> ci: 버전 업 관련 아무것도 없으면 스킵 처리

src/renderer/pages/pomodoro.tsx
- 빨리감기 ff 추가
- 사실 빨리감아지지는 않고 시간 단축이지만 ㅎ
=> feat: 개발시 초과시간까지 빠르게 테스트하기 위한 처리 추가

src/renderer/widgets/pomodoro/ui/home-screen.tsx
- 고양이 클릭시, 툴팁 메세지가 랜덤으로 바뀌도록 수정하였습니다 ~!
https://github.com/user-attachments/assets/8fce4f05-72a1-48ea-8869-e360a29fabf1
=> fix: 고양이 클릭시 메세지가 랜덤으로 나오도록 수정

src/main/main.ts, src/renderer/pages/mycat.tsx, src/renderer/pages/naming.tsx, src/renderer/pages/selection.tsx, src/renderer/shared/ui/guide.tsx, src/renderer/shared/ui/tooltip.tsx, src/renderer/widgets/pomodoro/ui/focus-screen.tsx, src/renderer/widgets/pomodoro/ui/home-screen.tsx, src/renderer/widgets/pomodoro/ui/rest-screen.tsx
- https://pomonyangteam.atlassian.net/browse/SCRUM-64
- 창 높이 800px -> 720px로
- 툴팁 메시지 드래그 방지
- 툴팁 위치 20px 더 밑으로 이동
- 서비스 가이드 문구 스타일도 변경
=> fix: 스프린트 1 QA 이슈 중 일부 수정

src/renderer/features/category/ui/change-category-drawer.tsx, src/renderer/pages/category.tsx
- qa 전 일부 구현 수정
- 별거 없어서 바로 머지함요
=> fix: 0402 카테고리 기능수정

src/renderer/features/category/ui/category-chip.tsx, src/renderer/features/category/ui/change-category-drawer.tsx, src/renderer/pages/category.tsx, src/renderer/shared/api/httpClient.ts, src/renderer/shared/ui/drawer.tsx, src/renderer/shared/utils/error.ts, src/renderer/widgets/pomodoro/ui/home-screen.tsx
- 이것저것 수정합니닷
- 이것도 일단 머지하고 피드백은 편히주십셔
=> fix: 카테고리 관련 수정 (0405)
